### ISSUE TITLE
File option not working with x5u

### ISSUE THREAD

**Issue by dualfade** [mBouamama/MyJWT#31]
When creating a token which uses a url fwd like ( x5u ):
Example: http://someondomain.com@x.x.x.x/.well-known/ --file jwks_with_x5c.json

The data gets clipped and the token is not generated using the --file <name>. You have to define it manually to make the token correct like below --

myjwt -p user=admin --x5u "http:/.api.targetdomain.com@3.140.201.195/jwks_with_x5c.json" --file jwks_with_x5c --key private.pem --crt hacker.crt --print <token>

If you have any questions just ping me. I cannot post the data here as i discovered it on an actual jwt x5u auth bypass challenge and it is exclusively stated to not share information. 

Great frigging tool !!!!! Color coding would be amazing on output.

Thanks.
~!>d

**Comment by mBouamama** [comment]
hi @dualfade 
Thx for your issue.

# File option not working with x5u
after pull request merged will be able to use **myjwt** like this:
```shell
myjwt -p user=admin --x5u "http:/.api.targetdomain.com@3.140.201.195" --file jwks_with_x5c --key private.pem --crt hacker.crt --print
```
## For more information
- if you don't use --file XXXX: jwks file name will be set to jwks_with_x5c.json
- if you don't add .json at the end like this jwks_with_x5c, it's work

If you are ok with that i'm merging the pull request #32.

# Color Coding output 
For your request color coding, its will be a great enhancement.
Do you have any idea for that?


Thanks.

**Comment by dualfade** [comment]
Yeah that would do it. That looks right. As far as color it's just a nice to have with colorama or something. Not needed. Was just thinking about easy readability on output.

Appreciate it.
~!>D

christopher.downs[at]protonmail.com, OSCP OSWE OSWP

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mBouamama** [comment]
lets go!!
i will do that so maybe next week.
Thx

**Comment by dualfade** [comment]
awesome ! let me know if you need anything. Rock ! ~!>D

**Comment by dualfade** [comment]
New rev pushed to BlackArch repos. Thank you again.

**Comment by dualfade** [comment]
You don't. ;) Awesome ! Let me know if you need me to test. ~!>D

**Comment by mBouamama** [comment]
Oh nice,
If i can, im curious to try to participate to publish new packages.
I will ping you when i create a pull request if you want to test and give me some advices.

**Comment by dualfade** [comment]
Normally we will update on a major release or bug fix ( if known ). I knew about this one since I submitted it ;)
